title: My Personal Website
email: your-email@example.com
description: >- # this means ignore newlines until "baseurl"
  A personal website for sharing my resume and technical notes/blog.
baseurl: "" # the subpath of your site, like "/blog"
url: "https://zephyrdhb.github.io" # the base hostname & protocol for your site
twitter_username: zephyrdhb
github_username:  zephyrdhb

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Custom variables
author:
  name: Your Name
  bio: Software Developer | Tech Enthusiast
  location: City, Country

collections:
  notes:
    output: true
    permalink: /notes/:path/